version: 0.2

env:
  variables:
    # REPOSITORY_URI and IMAGE_TAG are just placeholders to validate the CF template
    REPOSITORY_URI: "mock"
    IMAGE_TAG: "mock"
    CODEBUILD_RESOLVED_SOURCE_VERSION: "mock"
    DATABASE_URL: "mysql://docker:docker@localhost:16603/docker?atomic_requests=1&init_command=SET sql_mode='STRICT_TRANS_TABLES'"


phases:
  install:
    commands:
      - which docker || echo "docker not found"
      - python3 -V
      - cat /usr/local/bin/dockerd-entrypoint.sh
      - nohup su root -c "sh /usr/local/bin/dockerd-entrypoint.sh"
      #- nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo "Start MySQL docker container"
      - docker run --detach --name=test-mysql -e MYSQL_ROOT_PASSWORD=docker -e MYSQL_DATABASE=docker -e MYSQL_USER=docker -e MYSQL_PASSWORD=docker --publish 16603:3306 mysql:5.6
      - pip install --upgrade pip awscli
      - pip install -r requirements/test.txt
      - pip install -r requirements/build.txt

  build:
    commands:
      # - echo "$CODEBUILD_INITIATOR" | grep GitHub && flake8 | lintly --log || true
      - python manage.py wait_until_database_ready
      - pytest --cache-clear
  post_build:
    commands:
      - echo "Tests finally working"
cache:
  paths:
    - "/root/.cache/pip/**/*"
    - "/root/.cache/codecov.sh"
