version: '3.7'
services:
  # MySQL DB
  db:
    image: mysql:5.6
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "3306:3306"
