version: '3.7'
services:
  # MySQL DB
  db:
    image: mysql:5.6
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "3306:3306"
    networks:
        - briteaccess

  # Django API server
  briteaccess-api:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api
    networks:
        - gen3-api-layer
        - briteaccess
    command: /var/project/app/bin/run_local.sh
    environment:
      DATABASE_URL: mysql://docker:docker@db:3306/docker?atomic_requests=1&init_command=SET sql_mode='STRICT_TRANS_TABLES'
      DJANGO_SETTINGS_MODULE: briteaccess.settings.local
    volumes:
      - .:/var/app
      - ~/.ssh/:/root/.ssh/
      - ~/.aws/:/root/.aws/
    ports:
      - "8081:8081"
    links:
      - db:db
    depends_on:
      - db

networks:
  gen3-api-layer:
    external:
      name: gen3-api-layer
  briteaccess:
